apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-example-deployment-cache
  namespace: ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-corbo-cephfs
